fast_move = true
enable_fog = true
enable_clouds = false
enable_particles = false
viewing_range = 300
enable_damage = false
creative_mode = true
default_privs = interact, shout, fast
doubletap_jump = true
enable_pvp = false
mg_name = flat
mapgen_limit = 4096
time_speed = 0
display_gamma = 3
